---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install ansible
      apt: name=ansible state=latest
    - name: install git
      yum: name=git state=latest
